### ISSUE TITLE
[Question] Between loading teh tag at templates vs at render in views.py, which is easier?

### ISSUE THREAD

**Issue by simkimsia** [dabapps/django-zen-queries#45]
Loading the `zen_queries` tag at top of templates
```html
{% load zen_queries %}
```

vs
`queries_disabled` in the views
```python
def menu(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    with queries_disabled():
        return render(request, 'pizzas/menu.html', context)
```

Which one is easier or more recommended?

And why don't both use the same naming convention? Am I misunderstanding something?

## Postscript

Thanks for writing this library. I found this via the docs in `django-readers` which I already love.

**Comment by j4mie** [comment]
Just loading the template library doesn't do anything itself. To disable queries in a template, you have to use the {% queries_disabled %} template tag around the parts of the code that you don't want to be allowed to run queries.

I'd say the best way to use the library is to disable queries for the whole template render "by default" in the view (probably with the `zen_queries.render` shortcut rather than explicitly using the context manager like in your example, but your way is fine too). And then only use the template tags (`{% queries_dangerously_enabled %}) if you need to _enable_ queries in a specific (ideally small) part of your template.

**Comment by simkimsia** [comment]
> the zen_queries.render shortcut rather than explicitly using the context manager
Okay i see it now at https://github.com/dabapps/django-zen-queries#render-shortcut

I recommend writing it up as a `<code>` example and as I mentioned earlier have it at the tutorial/quickstart.

You can still repeat the codesnippet  at the `render-shortcut` section. 

You can have a sub-section in `render-shortcut` that is "Why we think this is better than using contextmanager's render?"
